spring:
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
    schema: classpath:schema.sql
    data: classpath:data.sql
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  logging:
    level:
      org.springframework.jdbc.core: DEBUG